ldexp: handle zero as multiplier - test-libc-nsz bugfix
The case for x = 0.0 was a missing edge case in the implementation of ldexp.

It was found when running this ldexp implementation against the
test-libc-nsz suite.

```
test-libc-nsz
└─ run libc-test math.ldexp (ReleaseSmall) failure
error: ========= expected this stdout: =========

       ========= but found: ====================
       ../libc-test/src/math/special/ldexp.h:1: RN ldexp(0x0p+0, 2147483647) want 0x0p+0 got inf, ulperr inf = inf + 0x0p+0
       ../libc-test/src/math/special/ldexp.h:3: RN ldexp(-0x0p+0, 2147483647) want -0x0p+0 got -inf, ulperr -inf = -inf + 0x0p+0
       ../libc-test/src/math/special/ldexp.h:10: bad fp exception: RN ldexp(0x1p+0, 2147483647)=inf, want INEXACT|OVERFLOW got 0

failed command: qemu-arm ./.zig-cache/o/../math.ldexp
```

The commit fixes the first two failures. However the third failure,
which blocks the port to ziglibc, needs a zig `fenv` implementation.
No changes to ldexp should be necessary after, as the OVERFLOW exception
will be raised when the `math.raiseOverflow` stub is implemented.