Move epoch time type aliases into `Datetime` due to probable compiler bug
For some reason, when the `Second` type alias is defined in the `epoch`
struct, we get [a seemingly unrelated Windows-only compiler error](https://codeberg.org/ziglang/zig/actions/runs/431/jobs/15/attempt/1):

```
error: 'behavior.type_info.test.type info: error set, error union info, anyerror' failed
```

This only happens with the `Second` type alias, not the others, and is
consistent between my CI job (linked above) and my Windows VM.

So the way I was able to fix this is by moving the `Second` type alias
into the `Datetime` struct, but I had to move the other units of time as
well for consistency.